# Generated by Django 5.0.7 on 2024-07-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not started', 'Not Started'), ('in progress', 'In Progress'), ('Incomplete', 'Incomplete'), ('completed', 'Completed')], max_length=50),
        ),
    ]
